/-
Copyright (c) 2026 Dagur Asgeirsson. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dagur Asgeirsson
-/
module

public meta import InternalLean.LFElab

/-!
# Registration helpers for user-declared type theories

This file contains generated anchor helpers, declaration-registration functions,
source-documentation capture, and shared internal-declaration registration utilities.
-/

@[expose] public meta section

open Lean Elab Command

namespace InternalLean

register_option internalLean.profileInternalDef : Bool := {
  defValue := false
  descr := "log InternalLean theory/internal registration profile entries as declarations \
    are checked"
}

/-- Record and optionally print one registration profile entry. -/
def recordInternalRegistrationProfile (p : InternalRegistrationProfile) : CoreM Unit := do
  registerInternalRegistrationProfile p
  if (← getBoolOption `internalLean.profileInternalDef) then
    logInfo m!"registration profile {p.theoryName}.{p.declName}: strategy={p.strategy}, \
      prior object defs={p.priorObjectDefs}, prior theorem(s)={p.priorJudgmentTheorems}, \
      old object defs rechecked={p.recheckedObjectDefs}, old theorem(s) rechecked=\
      {p.recheckedJudgmentTheorems}, incremental={p.incrementallyChecked}"

/-- Render a compact summary for the generated Lean-visible theory anchor. -/
def theoryAnchorSummaryString (sig : HLSignature) (sourceDoc? : Option String := none) : String :=
  let parentLine :=
    if sig.parents.isEmpty then
      "Parents: none"
    else
      s!"Parents: {String.intercalate ", " (sig.parents.toList.map (toString ·.eraseMacroScopes))}"
  let levelLine :=
    if sig.levelParams.isEmpty then
      "Level parameters: none"
    else
      s!"Level parameters: {String.intercalate ",
        " (sig.levelParams.toList.map (toString ·.eraseMacroScopes))}"
  let sourceDocLines :=
    match sourceDoc? with
    | some doc => ["Source documentation:", trimCapturedDoc doc, ""]
    | none => []
  String.intercalate "\n" <| sourceDocLines ++ [
    s!"Type theory `{sig.name.eraseMacroScopes}`.",
    "",
    "Lean-visible editor/navigation anchor generated by `declare_type_theory`.",
    "This declaration is a registry handle, not the trusted semantics of the theory.",
    "Checked LF artifacts and kernel-facing replay validators remain the trust boundary.",
    "",
    parentLine,
    levelLine,
    s!"Syntax sorts: {sig.syntaxSorts.size}",
    s!"Syntax abbreviations: {sig.syntaxAbbrevs.size}",
    s!"Judgments: {sig.judgments.size}",
    s!"Rules: {sig.rules.size}",
    s!"LF opaque constants: {sig.lfOpaqueConsts.size}",
    s!"LF object definitions: {sig.lfObjectDefs.size}",
    s!"LF judgment theorems: {sig.lfJudgmentTheorems.size}",
    "",
    s!"Useful diagnostics: `#check_type_theory_anchor {sig.name.eraseMacroScopes}`, \
      `#print_type_theory_anchor {sig.name.eraseMacroScopes}`, `#print_type_theory \
        {sig.name.eraseMacroScopes}`."
  ]

/-- Check registry and generated-anchor names before mutating the theory registry. -/
def ensureTheoryRegistrationNamesAvailable (theoryName : Name) : CommandElabM Unit := do
  if (← liftCoreM <| getTheory? theoryName).isSome then
    throwError "type theory '{theoryName}' has already been declared"
  let anchorName := theoryAnchorName theoryName
  if (← getEnv).contains anchorName then
    throwError "cannot create Lean-visible anchor '{anchorName}' for type theory '{theoryName}': \
      a Lean declaration with that name already exists"

/-- Add the generated Lean-visible anchor declaration for a type theory. -/
def addTheoryAnchorDeclaration (sig : HLSignature) (sourceDoc? : Option String) (
  rangeStx selectionRangeStx : Syntax) : CommandElabM Unit := do
  let anchorName := theoryAnchorName sig.name
  liftCoreM do
    let ty := mkConst ``TheoryAnchor
    let value := mkConst ``TheoryAnchor.mk
    let defVal ← mkDefinitionValInferringUnsafe anchorName [] ty value ReducibilityHints.abbrev
    addAndCompile (Declaration.defnDecl defVal)
  addDocStringCore anchorName (theoryAnchorSummaryString sig sourceDoc?)
  addDeclarationRangesFromSyntax anchorName rangeStx selectionRangeStx

/-- Resolved target information for a top-level `internal def`. -/
structure InternalDefTarget where
  /-- Owning object theory. -/
  theoryName : Name
  /-- Theory-local object declaration name. -/
  localName : Name
  /-- Lean-visible generated anchor name. -/
  anchorName : Name
  deriving Inhabited, Repr

/-- Return true when a parsed identifier is syntactically qualified. -/
def isQualifiedIdentName (n : Name) : Bool :=
  !n.getPrefix.isAnonymous

/-- Return the last component of a name as an unqualified name. -/
def nameLastComponent : Name → Name
  | .anonymous => .anonymous
  | .str _ s => .str .anonymous s
  | .num _ i => .num .anonymous i

/-- Resolve the target theory and local name for a top-level `internal def`. -/
def resolveInternalDefTarget (declName : Name) : CommandElabM InternalDefTarget := do
  let currentNs ← getCurrNamespace
  let currentTheory? ← liftCoreM do
    if currentNs.isAnonymous then
      pure none
    else if (← hasTheoryAnchor currentNs) then
      pure (some currentNs)
    else
      pure none
  let qualified := isQualifiedIdentName declName
  if qualified then
    let theoryName := declName.getPrefix
    unless ← liftCoreM (hasTheoryAnchor theoryName) do
      throwError "unknown type theory '{theoryName}'\n\nNo theory anchor named \
        '{theoryAnchorName theoryName}' is available in the current environment. Use \
          `declare_type_theory {theoryName} where ...` first, import the module that declares it, \
            or qualify the declaration name with the namespace of an existing theory."
    if let some nsTheory := currentTheory? then
      if nsTheory != theoryName then
        throwError "conflicting target theories for internal declaration '{declName}'\n\nThe \
          qualified name selects theory '{theoryName}', but the current namespace selects theory \
            '{nsTheory}'. Move the declaration to `namespace {theoryName}`, remove the \
              conflicting namespace, or use an unqualified name inside `{nsTheory}`."
    let localName := nameLastComponent declName
    if localName.isAnonymous then
      throwError "internal declaration '{declName}' is missing a local declaration name after \
        theory '{theoryName}'"
    return { theoryName, localName, anchorName := declName }
  else
    let some theoryName := currentTheory?
      | throwError "cannot infer target type theory for `internal def {declName}`\n\nWrite the \
        declaration inside a theory namespace, for example:\n  namespace TinyNatUX\n  internal \
          def {declName} : ... := ...\n  end TinyNatUX\n\nor qualify the declaration name:\n  \
            internal def TinyNatUX.{declName} : ... := ..."
    return { theoryName, localName := declName, anchorName := theoryName ++ declName }

/-- Check internal declaration registry and generated-anchor names before registration. -/
def ensureInternalDeclarationNamesAvailable (target : InternalDefTarget) : CommandElabM Unit := do
  let some sig ← liftCoreM <| getTheory? target.theoryName
    | throwError "unknown type theory '{target.theoryName}'"
  let flatSig ← liftCoreM <| flattenSignature sig
  if flatSig.containsName target.localName then
    throwError "declaration '{target.localName}' already exists in type theory \
      '{target.theoryName}' or one of its parents"
  if (← getEnv).contains target.anchorName then
    throwError "cannot create Lean-visible internal declaration anchor '{target.anchorName}': a \
      Lean declaration with that name already exists"

/-- Render a compact docstring for a generated internal declaration anchor. -/
def internalDeclarationAnchorDocString (target : InternalDefTarget) (typeExpr : ObjExpr) (
  admitted : Bool)
    (sourceDoc? : Option String := none) : String :=
  let sourceDocLines :=
    match sourceDoc? with
    | some doc => ["Source documentation:", trimCapturedDoc doc, ""]
    | none => []
  let admissionLines :=
    if admitted then
      [ "",
        "Admission: body is `sorry`.",
        "Annotation status: checked as an object-theory judgment/type.",
        "Replay status: explicit admitted/opaque placeholder; no successful body replay is \
          fabricated." ]
    else
      [ "",
        "Checked body: accepted by the current object-theory frontend.",
        "Replay status: direct-LF artifacts are stored with the checked theory when \
          supported." ]
  String.intercalate "\n" <| sourceDocLines ++
    [ s!"Internal declaration `{target.anchorName.eraseMacroScopes}` in type theory \
      `{target.theoryName.eraseMacroScopes}`.",
      "",
      s!"Object judgment/type: {typeExpr}",
      "Source command: `internal def`.",
      "This generated Lean declaration is an editor/navigation anchor, not the object declaration \
        as a Lean term." ] ++
    admissionLines ++
    ["",
      s!"Useful diagnostics: `#print_type_theory {target.theoryName.eraseMacroScopes}`, \
        `#lint_type_theory_sorries {target.theoryName.eraseMacroScopes}`."]

/-- Add a Lean-visible anchor for a top-level internal object declaration. -/
def addInternalDeclarationAnchor (target : InternalDefTarget) (typeExpr : ObjExpr) (admitted : Bool)
    (sourceDoc? : Option String) (rangeStx selectionRangeStx : Syntax) : CommandElabM Unit := do
  liftCoreM do
    let ty := mkConst ``InternalDeclarationAnchor
    let value := mkConst ``InternalDeclarationAnchor.mk
    let defVal ←
      mkDefinitionValInferringUnsafe target.anchorName [] ty value ReducibilityHints.abbrev
    addAndCompile (Declaration.defnDecl defVal)
  addDocStringCore target.anchorName (internalDeclarationAnchorDocString target typeExpr admitted
    sourceDoc?)
  addDeclarationRangesFromSyntax target.anchorName rangeStx selectionRangeStx

/-- Register a high-level theory signature, failing on duplicate names. -/
def registerTheory (sig : HLSignature) : CoreM Unit := do
  if (← getTheory? sig.name).isSome then
    throwError "type theory '{sig.name}' has already been declared"
  let headSig ← flattenSignature sig
  let sig ← elaborateImplicitAppsInSignatureWithEnv headSig sig
  let checked ← checkSignatureForRegistration sig
  recordInternalRegistrationProfile {
    theoryName := sig.name.eraseMacroScopes
    declName := `declare_type_theory
    strategy := "full declare_type_theory (streaming artifacts)"
    priorObjectDefs := 0
    priorJudgmentTheorems := 0
    recheckedObjectDefs := 0
    recheckedJudgmentTheorems := 0
    incrementallyChecked := 0 }
  modifyEnv fun env =>
    checkedTheoryExt.addEntry (theoryExt.addEntry env (.sig sig)) (.sig checked)

/-- Reopen an existing type theory and append one declaration block. -/
def registerTheoryBlockExtension (theoryName : Name) (block : HLTheoryBlock) : CoreM Unit := do
  let some sig ← getTheory? theoryName
    | throwError "unknown type theory '{theoryName}'"
  let some priorChecked ← getCheckedTheory? theoryName
    | throwError "no checked artifact stored for type theory '{theoryName}'"
  match unsupportedIncrementalTheoryBlockReason? block with
  | none =>
      let (blockForRegistry, checked) ←
        checkTheoryBlockExtensionIncremental theoryName sig priorChecked block
      let candidate := sig.appendBlock blockForRegistry
      recordInternalRegistrationProfile {
        theoryName := theoryName.eraseMacroScopes
        declName := `extend_type_theory
        strategy := "incremental extend_type_theory (streaming block)"
        priorObjectDefs := priorChecked.lfObjectDefs.size
        priorJudgmentTheorems := priorChecked.lfJudgmentTheorems.size
        recheckedObjectDefs := 0
        recheckedJudgmentTheorems := 0
        incrementallyChecked := theoryBlockIncrementalDeclCount blockForRegistry }
      modifyEnv fun env =>
        checkedTheoryExt.addEntry (theoryExt.addEntry env (.sig candidate)) (.sig checked)
  | some reason =>
      let candidate := sig.appendBlock block
      let headSig ← flattenSignature candidate
      let candidate ← elaborateImplicitAppsInSignatureWithEnv headSig candidate
      let checked ← checkSignatureForRegistration candidate
      recordInternalRegistrationProfile {
        theoryName := theoryName.eraseMacroScopes
        declName := `extend_type_theory
        strategy := s!"full fallback extend_type_theory: {reason}"
        priorObjectDefs := priorChecked.lfObjectDefs.size
        priorJudgmentTheorems := priorChecked.lfJudgmentTheorems.size
        recheckedObjectDefs := priorChecked.lfObjectDefs.size
        recheckedJudgmentTheorems := priorChecked.lfJudgmentTheorems.size
        incrementallyChecked := 0 }
      modifyEnv fun env =>
        checkedTheoryExt.addEntry (theoryExt.addEntry env (.sig candidate)) (.sig checked)

/-- Split leading named function arrows in an admitted LF opaque annotation into a shallow
LF parameter telescope. This lets users write
`internal def f : (x : A) → B x := sorry` for a visible postulated LF constant. -/
partial def splitAdmittedLFOpaqueType (params : Array HLBinding) :
  ObjExpr → Array HLBinding × ObjExpr
  | .funArrow (some x) A B | .arrow (some x) A B =>
      splitAdmittedLFOpaqueType (params.push { name := x, typeExpr := A, visibility :=
        .explicit }) B
  | typeExpr => (params, typeExpr)

/-- Register an explicitly admitted internal declaration as a typed LF opaque constant.

This is the visible postulate path for generic LF metadata theories: the annotation is
checked by the LF metadata checker, the body remains admitted, and later LF definitions or
judgment theorems may refer to the admitted name as an opaque theory-local constant. -/
def registerAdmittedInternalLFOpaque (theoryName anchorName localName : Name)
    (params : Array HLBinding) (typeExpr : ObjExpr) : CoreM Unit := do
  let some sig ← getTheory? theoryName
    | throwError "unknown type theory '{theoryName}'"
  let flatSig ← flattenSignature sig
  if flatSig.containsName localName then
    throwError "declaration '{localName}' already exists in type theory '{theoryName}' or one of \
      its parents"
  let (params, resultTypeExpr) := splitAdmittedLFOpaqueType params typeExpr
  let d : LFOpaqueConstDecl := {
    name := localName
    arity? := some params.size
    params := params
    typeExpr? := some resultTypeExpr
  }
  let flatSig := { flatSig with lfOpaqueConsts := flatSig.lfOpaqueConsts.push d }
  let d ← elaborateImplicitAppsInLFOpaqueConstDecl flatSig d
  let candidate := { sig with lfOpaqueConsts := sig.lfOpaqueConsts.push d }
  let checked ← checkSignatureForRegistration candidate
  let admission : InternalAdmission := {
    theoryName, declName := localName, anchorName, params := d.params,
    typeExpr := d.typeExpr?.getD resultTypeExpr, kind := .lfOpaque }
  recordInternalRegistrationProfile {
    theoryName := theoryName
    declName := localName.eraseMacroScopes
    strategy := "full admitted LF opaque"
    priorObjectDefs := checked.lfObjectDefs.size
    priorJudgmentTheorems := checked.lfJudgmentTheorems.size
    recheckedObjectDefs := checked.lfObjectDefs.size
    recheckedJudgmentTheorems := checked.lfJudgmentTheorems.size
    incrementallyChecked := 0 }
  modifyEnv fun env =>
    let env := theoryExt.addEntry env (.lfOpaqueConst theoryName d)
    let env := checkedTheoryExt.addEntry env (.sig checked)
    internalAdmissionExt.addEntry env (.admission admission)

/-- Previously checked LF definition result types, used as available local type information for
validating an admitted custom-judgment statement. -/
def checkedLFDefinitionTypeMap (checked : CheckedSignature) : LFLocalTypes :=
  checkedLFDefinitionTypeMapFromDefs checked.lfObjectDefs

/-- Append one checked LF object definition to an already checked signature. -/
def appendCheckedLFObjectDef (checked : CheckedSignature) (d : CheckedLFObjectDef) :
    CheckedSignature :=
  appendCheckedTheoryDelta checked { objectDefs := #[d] }

/-- Append one checked LF judgment theorem to an already checked signature. -/
def appendCheckedLFJudgmentTheorem (checked : CheckedSignature) (t : CheckedLFJudgmentTheorem) :
    CheckedSignature :=
  appendCheckedTheoryDelta checked { judgmentTheorems := #[t] }

/-- Register an explicitly admitted internal declaration whose annotation is a custom LF
judgment statement.

Unlike an admitted LF opaque, this does not add a new object constant to the theory. It
records a specific theorem-shaped admission for model transport and linting after checking
that the statement is a well-formed LF judgment over the current signature. -/
def registerAdmittedInternalLFJudgmentTheorem (theoryName anchorName localName : Name)
    (params : Array HLBinding) (typeExpr : ObjExpr) : CoreM Unit := do
  if !params.isEmpty then
    throwError "LF judgment admissions do not yet support source binders; write a closed judgment \
      statement or introduce explicit LF objects first"
  let some sig ← getTheory? theoryName
    | throwError "unknown type theory '{theoryName}'"
  let flatSig ← flattenSignature sig
  if flatSig.containsName localName then
    throwError "declaration '{localName}' already exists in type theory '{theoryName}' or one of \
      its parents"
  let some checked ← getCheckedTheory? theoryName
    | throwError "no checked artifact stored for type theory '{theoryName}'"
  let knownLFDefTypes := checkedLFDefinitionTypeMap checked
  let typeExpr ←
    elaborateImplicitAppsInExpr flatSig knownLFDefTypes {} "admitted internal \
      declaration" localName "statement" none typeExpr
  let lfGlobals := lfKnownGlobalNames flatSig
  let opaqueArities := lfOpaqueArities flatSig
  let globalHeads := lfGlobalHeadInfo flatSig
  let judgmentArities : NameMap Nat := flatSig.judgments.foldl (init := {}) fun acc j =>
    acc.insert j.name.eraseMacroScopes j.params.size
  checkKnownNamesInLFExpr flatSig lfGlobals {} opaqueArities "admitted internal \
    declaration" localName "statement" typeExpr
  checkLFDefinitionReferencesAvailable flatSig globalHeads knownLFDefTypes "admitted internal \
    declaration" localName "statement" (locals := {}) typeExpr
  checkLFSyntaxSortArgumentsInExpr flatSig "admitted internal \
    declaration" localName "statement" knownLFDefTypes typeExpr
  checkLFInferableApplicationArguments flatSig "admitted internal \
    declaration" localName "statement" knownLFDefTypes typeExpr
  let judgmentHead ← checkRuleJudgmentHead flatSig judgmentArities localName "statement" typeExpr
  let (_, judgmentArgs) := splitObjApp typeExpr
  checkLFJudgmentArgumentsWithKnownTypes flatSig "admitted internal \
    declaration" localName "statement"
    knownLFDefTypes judgmentHead.name judgmentArgs
  discard



















    <| resolveLFExpr flatSig globalHeads {} "admitted internal \
      declaration" localName "statement" typeExpr
  let admission : InternalAdmission := {
    theoryName := theoryName
    declName := localName
    anchorName := anchorName
    params := params
    typeExpr := typeExpr
    kind := .judgmentTheorem
  }
  recordInternalRegistrationProfile {
    theoryName := theoryName
    declName := localName.eraseMacroScopes
    strategy := "incremental LF judgment admission"
    priorObjectDefs := checked.lfObjectDefs.size
    priorJudgmentTheorems := checked.lfJudgmentTheorems.size
    recheckedObjectDefs := 0
    recheckedJudgmentTheorems := 0
    incrementallyChecked := 1 }
  modifyEnv fun env => internalAdmissionExt.addEntry env (.admission admission)

/-- Register a top-level staged LF/object definition in an existing theory. -/
def registerLFObjectDef (theoryName : Name) (d : LFObjectDefDecl) : CoreM Unit := do
  let some sig ← getTheory? theoryName
    | throwError "unknown type theory '{theoryName}'"
  let flatSig ← flattenSignature sig
  if flatSig.containsName d.name then
    throwError "declaration '{d.name}' already exists in type theory '{theoryName}' or one of its \
      parents"
  let some checked ← getCheckedTheory? theoryName
    | throwError "no checked artifact stored for type theory '{theoryName}'"
  let knownTypes := checkedLFDefinitionTypeMap checked
  let flatSigWithNew := { flatSig with lfObjectDefs := flatSig.lfObjectDefs.push d }
  let dForRegistry ← elaborateImplicitAppsInLFObjectDef flatSigWithNew knownTypes d
  let typeExpr ←
    expandSyntaxAbbrevsInExpr flatSigWithNew "lf_def" dForRegistry.name "type" {}
      (flatSigWithNew.syntaxAbbrevs.size + 1) dForRegistry.typeExpr
  let value ←
    expandSyntaxAbbrevsInExpr flatSigWithNew "lf_def" dForRegistry.name "value" {}
      (flatSigWithNew.syntaxAbbrevs.size + 1) dForRegistry.value
  let dForCheck := {
    dForRegistry with
    name := dForRegistry.name.eraseMacroScopes
    typeExpr := typeExpr
    value := value }
  let flatForCheck := { flatSig with lfObjectDefs := flatSig.lfObjectDefs.push dForCheck }
  let checkedDef ←
    checkOneLFObjectDefArtifactInSignature flatForCheck dForCheck checked.lfObjectDefs
  let checked' := appendCheckedLFObjectDef checked checkedDef
  recordInternalRegistrationProfile {
    theoryName := theoryName
    declName := d.name.eraseMacroScopes
    strategy := "incremental LF object definition"
    priorObjectDefs := checked.lfObjectDefs.size
    priorJudgmentTheorems := checked.lfJudgmentTheorems.size
    recheckedObjectDefs := 0
    recheckedJudgmentTheorems := 0
    incrementallyChecked := 1 }
  modifyEnv fun env =>
    checkedTheoryExt.addEntry (theoryExt.addEntry env (.lfObjectDef theoryName dForRegistry))
      (.sig checked')

/-- Register a top-level staged LF judgment theorem in an existing theory. -/
def registerLFJudgmentTheorem (theoryName : Name) (t : LFJudgmentTheoremDecl) : CoreM Unit := do
  let some sig ← getTheory? theoryName
    | throwError "unknown type theory '{theoryName}'"
  let flatSig ← flattenSignature sig
  if flatSig.containsName t.name then
    throwError "declaration '{t.name}' already exists in type theory '{theoryName}' or one of its \
      parents"
  let some checked ← getCheckedTheory? theoryName
    | throwError "no checked artifact stored for type theory '{theoryName}'"
  let knownTypes := checkedLFDefinitionTypeMap checked
  let flatSigWithNew := { flatSig with lfJudgmentTheorems := flatSig.lfJudgmentTheorems.push t }
  let tForRegistry ← elaborateImplicitAppsInLFJudgmentTheorem flatSigWithNew knownTypes t
  let binders ← expandSyntaxAbbrevsInBindings flatSigWithNew "judgment_theorem" tForRegistry.name
    tForRegistry.binders
  let locals := binders.foldl (fun locals b => locals.insert b.name.eraseMacroScopes) {}
  let judgmentExpr ←
    expandSyntaxAbbrevsInExpr flatSigWithNew "judgment_theorem" tForRegistry.name "statement"
      locals (flatSigWithNew.syntaxAbbrevs.size + 1) tForRegistry.judgmentExpr
  let proof ←
    expandSyntaxAbbrevsInExpr flatSigWithNew "judgment_theorem" tForRegistry.name "proof"
      locals (flatSigWithNew.syntaxAbbrevs.size + 1) tForRegistry.proof
  let tForCheck := {
    tForRegistry with
    name := tForRegistry.name.eraseMacroScopes
    binders := binders
    judgmentExpr := judgmentExpr
    proof := proof }
  let flatForCheck := {
    flatSig with lfJudgmentTheorems := flatSig.lfJudgmentTheorems.push tForCheck }
  let checkedTheoremRaw ←
    checkOneLFJudgmentTheoremArtifactInSignature flatForCheck checked.lfRules tForCheck
      checked.lfObjectDefs checked.lfJudgmentTheorems
  let checkedTheorem ←
    validateIncrementalLFTheoremKernelReplay flatForCheck checked checkedTheoremRaw
  let checked' := appendCheckedLFJudgmentTheorem checked checkedTheorem
  recordInternalRegistrationProfile {
    theoryName := theoryName
    declName := t.name.eraseMacroScopes
    strategy := "incremental LF judgment theorem"
    priorObjectDefs := checked.lfObjectDefs.size
    priorJudgmentTheorems := checked.lfJudgmentTheorems.size
    recheckedObjectDefs := 0
    recheckedJudgmentTheorems := 0
    incrementallyChecked := 1 }
  modifyEnv fun env =>
    checkedTheoryExt.addEntry (theoryExt.addEntry env (.lfJudgmentTheorem theoryName tForRegistry))
      (.sig checked')

/-- Register a theory-local ergonomic object macro. -/
def registerObjectMacro (theoryName : Name) (mac : ObjectMacro) : CoreM Unit := do
  let some sig ← getTheory? theoryName
    | throwError "unknown type theory '{theoryName}'"
  let flatSig ← flattenSignature sig
  if flatSig.containsName mac.name then
    throwError "object macro '{mac.name}' conflicts with an existing declaration in type theory \
      '{theoryName}' or one of its parents"
  if flatSig.macros.any (fun old => sameObjectName old.name mac.name) then
    throwError "object macro '{mac.name}' has already been declared in type theory '{theoryName}' \
      or one of its parents"
  modifyEnv fun env => theoryExt.addEntry env (.macro theoryName mac)

/-- Register non-semantic role metadata for a theory-local object constant or macro. -/
def registerObjectRole (theoryName : Name) (role : ObjectRole) : CoreM Unit := do
  let some sig ← getTheory? theoryName
    | throwError "unknown type theory '{theoryName}'"
  let flatSig ← flattenSignature sig
  if !(flatSig.containsName role.name) && !(flatSig.macros.any (fun mac =>
    sameObjectName mac.name role.name)) then
    throwError "cannot assign a role to unknown object name '{role.name}' in type theory \
      '{theoryName}'"
  modifyEnv fun env => theoryExt.addEntry env (.role theoryName role)

/-- Check that declaration names in a single theory block are unique. -/
def checkNoDuplicateBlockNames (block : HLTheoryBlock) : CommandElabM Unit := do
  let mut seen : NameSet := {}
  for (kind, n) in
      (block.syntaxSorts.map (fun d => ("syntax-sort", d.name)) ++
        block.syntaxAbbrevs.map (fun d => ("syntax abbreviation", d.name)) ++
        block.contextZones.map (fun d => ("context-zone", d.name)) ++
        block.binderClasses.map (fun d => ("binder class", d.name)) ++
        block.judgments.map (fun d => ("judgment", d.name)) ++
        block.rules.map (fun d => ("rule", d.name)) ++
        block.sideConditionSolvers.map (fun d => ("side-condition solver", d.name)) ++
        block.conversionPlugins.map (fun d => ("conversion plugin", d.name)) ++
        block.lfOpaqueConsts.map (fun d => ("LF opaque constant", d.name)) ++
        block.lfObjectDefs.map (fun d => ("LF object definition", d.name)) ++
        block.lfJudgmentTheorems.map (fun d => ("LF judgment theorem", d.name))) do
    if seen.contains n then
      throwError "duplicate {kind} declaration '{n}' in type-theory block"
    seen := seen.insert n

/-- Convert parsed declaration-block metadata into signature fields. -/
def signatureWithBlock (sig : HLSignature) (block : HLTheoryBlock) : HLSignature :=
  { sig with
    syntaxSorts := block.syntaxSorts
    syntaxAbbrevs := block.syntaxAbbrevs
    syntaxSortRoles := block.syntaxSortRoles
    contextZones := block.contextZones
    binderClasses := block.binderClasses
    judgments := block.judgments
    judgmentRoles := block.judgmentRoles
    rules := block.rules
    ruleRoles := block.ruleRoles
    rewriteRelations := block.rewriteRelations
    rewriteSymmetries := block.rewriteSymmetries
    rewriteCongruences := block.rewriteCongruences
    transportRules := block.transportRules
    transportPositions := block.transportPositions
    sideConditionSolvers := block.sideConditionSolvers
    conversionPlugins := block.conversionPlugins
    lfOpaqueConsts := block.lfOpaqueConsts
    modelVisibilities := block.modelVisibilities
    modelSections := block.modelSections
    modelSectionMemberships := block.modelSectionMemberships
    lfObjectDefs := block.lfObjectDefs
    lfJudgmentTheorems := block.lfJudgmentTheorems }

/-- Extract user text from a Lean documentation-comment syntax node. -/
def docCommentString (doc : Syntax) : CommandElabM String := do
  match doc[1] with
  | .atom _ val =>
      pure <| trimCapturedDoc (String.Pos.Raw.extract val 0 (val.rawEndPos.unoffsetBy ⟨2⟩))
  | _ => throwErrorAt doc "unexpected doc string syntax{indentD doc}"

/-- Extract an optional documentation-comment text. -/
def optDocCommentString? :
  Option (TSyntax ``Parser.Command.docComment) → CommandElabM (Option String)
  | none => pure none
  | some doc => some <$> docCommentString doc.raw

/-- Capture a source doc comment immediately preceding a syntax item by scanning source text.

The `ttDecl` parser cannot safely include `docComment` directly because `declare_type_theory`
uses a repetition of `ttDecl`s. A direct doc-comment alternative would greedily consume the
next top-level command docstring after the theory block. Scanning source ranges keeps ordinary
Lean doc comments usable inside the block without changing the parser boundary. -/
def leadingDocCommentBefore? (stx : Syntax) : CommandElabM (Option String) := do
  let some pos := stx.getPos? (canonicalOnly := true)
    | return none
  let fm ← getFileMap
  let pre := String.Pos.Raw.extract fm.source 0 pos
  let trimmed := pre.trimAsciiEnd.toString
  unless trimmed.endsWith "-/" do
    return none
  let parts := trimmed.splitOn "/--"
  match parts.reverse with
  | [] | [_] => return none
  | last :: _ =>
      unless last.endsWith "-/" do
        return none
      let body := (last.dropEnd 2).toString
      return some (trimCapturedDoc body)

/-- Find the first doc-comment node inside syntax. -/
partial def findDocCommentSyntax? (stx : Syntax) : Option Syntax :=
  if stx.getKind == ``Parser.Command.docComment then
    some stx
  else
    match stx with
    | .node _ _ args =>
        args.findSome? findDocCommentSyntax?
    | _ => none

/-- Extract an inline doc comment parsed as part of a documented declaration-block item. -/
def ttDeclDocComment? (decl : TSyntax `ttDecl) : CommandElabM (Option String) := do
  match findDocCommentSyntax? decl.raw with
  | some doc => some <$> docCommentString doc
  | none => pure none

/-- Return the documentation role and source name for a declaration-block item, if it is
public-facing. -/
def sourceDocRoleAndNameOfTTDecl? (decl : TSyntax `ttDecl) :
  CommandElabM (Option (SourceDocRole × Name)) := do
  match decl with
  | `(ttDecl| syntax_sort $n:ident $bs:ttBinder*) =>
      let _ := bs.size
      pure <| some (.syntaxSort, n.getId)
  | `(ttDecl| $doc:docComment syntax_sort $n:ident $bs:ttBinder*) =>
      let _ := doc.raw; let _ := bs.size
      pure <| some (.syntaxSort, n.getId)
  | `(ttDecl| syntax_abbrev $n:ident $bs:ttBinder* := $value:ttExpr) =>
      let _ := bs.size; let _ := value.raw
      pure <| some (.syntaxAbbrev, n.getId)
  | `(ttDecl| $doc:docComment syntax_abbrev $n:ident $bs:ttBinder* := $value:ttExpr) =>
      let _ := doc.raw; let _ := bs.size; let _ := value.raw
      pure <| some (.syntaxAbbrev, n.getId)
  | `(ttDecl| context_zone $n:ident : $sortName:ident) =>
      let _ := sortName.getId
      pure <| some (.contextZone, n.getId)
  | `(ttDecl| context_zone $n:ident : $sortName:ident depends_on $deps:ident,*) =>
      let _ := sortName.getId; let _ := deps.getElems.size
      pure <| some (.contextZone, n.getId)
  | `(ttDecl| binder_class $n:ident : $sortName:ident in $zoneName:ident) =>
      let _ := sortName.getId; let _ := zoneName.getId
      pure <| some (.binderClass, n.getId)
  | `(ttDecl| binder_class $n:ident :
    $sortName:ident in $zoneName:ident depends_on $deps:ident,*) =>
      let _ := sortName.getId; let _ := zoneName.getId; let _ := deps.getElems.size
      pure <| some (.binderClass, n.getId)
  | `(ttDecl| judgment $n:ident $bs:ttBinder*) =>
      let _ := bs.size
      pure <| some (.judgment, n.getId)
  | `(ttDecl| $doc:docComment judgment $n:ident $bs:ttBinder*) =>
      let _ := doc.raw; let _ := bs.size
      pure <| some (.judgment, n.getId)
  | `(ttDecl| rule $n:ident $bs:ttBinder* : $conclStx:ttExpr) =>
      let _ := bs.size; let _ := conclStx.raw
      pure <| some (.rule, n.getId)
  | `(ttDecl| $doc:docComment rule $n:ident $bs:ttBinder* : $conclStx:ttExpr) =>
      let _ := doc.raw; let _ := bs.size; let _ := conclStx.raw
      pure <| some (.rule, n.getId)
  | `(ttDecl| rule $n:ident $bs:ttBinder* where $items:ttRuleItem*) =>
      let _ := bs.size; let _ := items.size
      pure <| some (.rule, n.getId)
  | `(ttDecl| $doc:docComment rule $n:ident $bs:ttBinder* where $items:ttRuleItem*) =>
      let _ := doc.raw; let _ := bs.size; let _ := items.size
      pure <| some (.rule, n.getId)
  | `(ttDecl| side_condition_solver $n:ident) => pure <| some (.sideConditionSolver, n.getId)
  | `(ttDecl| conversion_plugin $n:ident) => pure <| some (.conversionPlugin, n.getId)
  | `(ttDecl| conversion_plugin $n:ident opaque) => pure <| some (.conversionPlugin, n.getId)
  | `(ttDecl| conversion_plugin $n:ident external_certificate) => pure <| some (.conversionPlugin,
    n.getId)
  | `(ttDecl| conversion_plugin $n:ident executable) => pure <| some (.conversionPlugin, n.getId)
  | `(ttDecl| $doc:docComment conversion_plugin $n:ident) =>
      let _ := doc.raw
      pure <| some (.conversionPlugin, n.getId)
  | `(ttDecl| $doc:docComment conversion_plugin $n:ident opaque) =>
      let _ := doc.raw
      pure <| some (.conversionPlugin, n.getId)
  | `(ttDecl| $doc:docComment conversion_plugin $n:ident external_certificate) =>
      let _ := doc.raw
      pure <| some (.conversionPlugin, n.getId)
  | `(ttDecl| $doc:docComment conversion_plugin $n:ident executable) =>
      let _ := doc.raw
      pure <| some (.conversionPlugin, n.getId)
  | `(ttDecl| lf_opaque $n:ident) => pure <| some (.lfOpaque, n.getId)
  | `(ttDecl| lf_opaque $n:ident / $arity:num) =>
      let _ := arity.getNat
      pure <| some (.lfOpaque, n.getId)
  | `(ttDecl| lf_opaque $n:ident $bs:ttBinder* : $ty:ttExpr) =>
      let _ := bs.size; let _ := ty.raw
      pure <| some (.lfOpaque, n.getId)
  | `(ttDecl| $doc:docComment lf_opaque $n:ident $bs:ttBinder* : $ty:ttExpr) =>
      let _ := doc.raw; let _ := bs.size; let _ := ty.raw
      pure <| some (.lfOpaque, n.getId)
  | `(ttDecl| lf_def $n:ident : $ty:ttExpr := $value:ttExpr) =>
      let _ := ty.raw; let _ := value.raw
      pure <| some (.lfObjectDef, n.getId)
  | `(ttDecl| $doc:docComment lf_def $n:ident : $ty:ttExpr := $value:ttExpr) =>
      let _ := doc.raw; let _ := ty.raw; let _ := value.raw
      pure <| some (.lfObjectDef, n.getId)
  | `(ttDecl| judgment_theorem $n:ident $bs:ttBinder* : $j:ttExpr := $proof:ttExpr) =>
      let _ := bs.size; let _ := j.raw; let _ := proof.raw
      pure <| some (.lfJudgmentTheorem, n.getId)
  | `(ttDecl| $doc:docComment judgment_theorem $n:ident $bs:ttBinder* : $j:ttExpr :=
    $proof:ttExpr) =>
      let _ := doc.raw; let _ := bs.size; let _ := j.raw; let _ := proof.raw
      pure <| some (.lfJudgmentTheorem, n.getId)
  | _ => pure none

/-- Capture source docstrings from documented items in a `declare_type_theory` block. -/
def sourceDocsFromTheoryBlock (theoryName : Name) (decls : TSyntaxArray `ttDecl) :
  CommandElabM (Array SourceDoc) := do
  let mut out := #[]
  for decl in decls do
    let doc? ← match ← ttDeclDocComment? decl with
      | some doc => pure (some doc)
      | none => leadingDocCommentBefore? decl.raw
    if let some doc := doc? then
      if let some (role, sourceName) ← sourceDocRoleAndNameOfTTDecl? decl then
        out := out.push { theoryName, role, sourceName, doc := trimCapturedDoc doc }
  pure out

/-- Register a batch of captured source docstrings. -/
def registerSourceDocs (docs : Array SourceDoc) : CoreM Unit := do
  for d in docs do
    registerSourceDoc d.theoryName d.role d.sourceName d.doc



syntax (name := declareInternalLeanWhere)
  docComment ? "declare_type_theory " ident " where" ppLine ttDecl* : command
syntax (name := declareInternalLeanLevelWhere)
  docComment ? "declare_type_theory " ident "{" ident,* "}" " where" ppLine ttDecl* : command
syntax (name := declareInternalLeanExtendsWhere)
  docComment ? "declare_type_theory " ident " extends " ident,+ " where" ppLine ttDecl* : command
syntax (name := declareInternalLeanLevelExtendsWhere)
  docComment ? "declare_type_theory \
    " ident "{" ident,* "}" " extends " ident,+ " where" ppLine ttDecl* : command
syntax (name := extendInternalLeanWhere)
  docComment ? "extend_type_theory " ident " where" ppLine ttDecl* : command

/-- Shared elaboration path for all `declare_type_theory` syntactic variants. -/
def elabDeclareInternalLean (doc? : Option (TSyntax ``Parser.Command.docComment)) (nm : Ident)
    (levelParams parents : Array Name) (decls : TSyntaxArray `ttDecl) : CommandElabM Unit := do
  let block ← elabHLTheoryBlock decls
  checkNoDuplicateBlockNames block
  let sig := signatureWithBlock { name := nm.getId, parents, levelParams } block
  ensureTheoryRegistrationNamesAvailable sig.name
  let sourceDoc? ← optDocCommentString? doc?
  let mut sourceDocs ← sourceDocsFromTheoryBlock sig.name decls
  if let some doc := sourceDoc? then
    sourceDocs := sourceDocs.push {
      theoryName := sig.name
      role := .theory
      sourceName := sig.name
      doc := doc
    }
  liftCoreM do
    registerTheory sig
    registerSourceDocs sourceDocs
  addTheoryAnchorDeclaration sig sourceDoc? (← getRef) nm

/-- Shared elaboration path for `extend_type_theory`, preserving the original Lean-visible
theory anchor while registration uses the incremental checker or a full fallback. -/
def elabExtendInternalLean (doc? : Option (TSyntax ``Parser.Command.docComment)) (nm : Ident)
    (decls : TSyntaxArray `ttDecl) : CommandElabM Unit := do
  let block ← elabHLTheoryBlock decls
  checkNoDuplicateBlockNames block
  unless (← liftCoreM <| getTheory? nm.getId).isSome do
    throwError "unknown type theory '{nm.getId}'; use `declare_type_theory {nm.getId} where ...` \
      before `extend_type_theory`"
  let sourceDoc? ← optDocCommentString? doc?
  let mut sourceDocs ← sourceDocsFromTheoryBlock nm.getId decls
  if let some doc := sourceDoc? then
    sourceDocs := sourceDocs.push {
      theoryName := nm.getId
      role := .theory
      sourceName := nm.getId
      doc := doc
    }
  liftCoreM do
    registerTheoryBlockExtension nm.getId block
    registerSourceDocs sourceDocs

elab_rules : command
  | `($[$doc?:docComment]? declare_type_theory $nm:ident where $decls:ttDecl*) => do
      elabDeclareInternalLean doc? nm #[] #[] decls
  | `($[$doc?:docComment]? declare_type_theory $nm:ident {$levels:ident,*} where $decls:ttDecl*) =>
    do
      elabDeclareInternalLean doc? nm (levels.getElems.map (·.getId)) #[] decls
  | `($[$doc?:docComment]? declare_type_theory $nm:ident extends $parents:ident,* where
    $decls:ttDecl*) => do
      elabDeclareInternalLean doc? nm #[] (parents.getElems.map (·.getId)) decls
  | `($[$doc?:docComment]? declare_type_theory $nm:ident {$levels:ident,*} extends $parents:ident,*
    where $decls:ttDecl*) => do
      elabDeclareInternalLean doc? nm (levels.getElems.map (·.getId)) (
        parents.getElems.map (·.getId)) decls
  | `($[$doc?:docComment]? extend_type_theory $nm:ident where $decls:ttDecl*) => do
      elabExtendInternalLean doc? nm decls

/- Legacy `object_def`/`object_theorem` commands were removed. Use `internal def` over
   direct LF metadata. -/



end InternalLean
