/-
Copyright (c) 2026 Dagur Asgeirsson. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dagur Asgeirsson
-/
module

public import InternalLean.Command

/-!
# Lean-visible theory anchor tests

These tests exercise UX-1 anchors generated by `declare_type_theory`.
-/

@[expose] public section

open Lean

declare_type_theory AnchorSmoke where
  syntax_sort Ctx
  syntax_sort Tm (Γ : Ctx)
  judgment EqTm {Γ : Ctx} (a : Tm Γ) (b : Tm Γ) (A : Tm Γ)
  lf_opaque emptyCtx : Ctx
  lf_opaque obj : Tm emptyCtx
  lf_def objAlias : Tm emptyCtx := obj

#check AnchorSmoke.theory
#check_type_theory_anchor AnchorSmoke
#print_type_theory_anchor AnchorSmoke

#eval show CoreM Unit from do
  let anchorName := InternalLean.theoryAnchorName `AnchorSmoke
  unless (← InternalLean.hasTheoryAnchor `AnchorSmoke) do
    throwError "missing theory anchor {anchorName}"
  let some doc ← findDocString? (← getEnv) anchorName
    | throwError "missing docstring for theory anchor {anchorName}"
  unless doc.contains "Lean-visible editor/navigation anchor" do
    throwError "unexpected docstring for theory anchor {anchorName}: {doc}"
  let eqAnchorName := InternalLean.internalTheoryDeclarationAnchorName `AnchorSmoke `EqTm
  let some eqDoc ← findDocString? (← getEnv) eqAnchorName
    | throwError "missing docstring for source anchor {eqAnchorName}"
  let expectedEq := "`judgment EqTm {Γ : Ctx} (a : Tm Γ) (b : Tm Γ) (A : Tm Γ)`"
  unless eqDoc.contains expectedEq do
    throwError "unexpected docstring for judgment source anchor {eqAnchorName}: {eqDoc}"
  let aliasAnchorName := InternalLean.internalTheoryDeclarationAnchorName `AnchorSmoke `objAlias
  let some aliasDoc ← findDocString? (← getEnv) aliasAnchorName
    | throwError "missing docstring for source anchor {aliasAnchorName}"
  unless aliasDoc.contains "`lf_def objAlias : Tm emptyCtx := obj`" do
    throwError "unexpected docstring for LF definition source anchor {aliasAnchorName}: \
      {aliasDoc}"

/-- Preexisting declaration used to test anchor-name collision diagnostics. -/
def AnchorCollision.theory : Unit := ()

/-- error: cannot create Lean-visible anchor 'AnchorCollision.theory' for type theory
'AnchorCollision': a Lean declaration with that name already exists -/
#guard_msgs (whitespace := lax) in
declare_type_theory AnchorCollision where
  syntax_sort Obj
