/-
Copyright (c) 2026 Dagur Asgeirsson. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dagur Asgeirsson
-/
module

public import InternalLean.Command

/-!
# Lean-visible theory anchor tests

These tests exercise UX-1 anchors generated by `declare_type_theory`.
-/

@[expose] public section

open Lean

declare_type_theory AnchorSmoke where
  syntax_sort Obj
  lf_opaque obj : Obj

#check AnchorSmoke.theory
#check_type_theory_anchor AnchorSmoke
#print_type_theory_anchor AnchorSmoke

#eval show CoreM Unit from do
  let anchorName := InternalLean.theoryAnchorName `AnchorSmoke
  unless (← InternalLean.hasTheoryAnchor `AnchorSmoke) do
    throwError "missing theory anchor {anchorName}"
  let some doc ← findDocString? (← getEnv) anchorName
    | throwError "missing docstring for theory anchor {anchorName}"
  unless doc.contains "Lean-visible editor/navigation anchor" do
    throwError "unexpected docstring for theory anchor {anchorName}: {doc}"

/-- Preexisting declaration used to test anchor-name collision diagnostics. -/
def AnchorCollision.theory : InternalLean.TheoryAnchor := .mk

/-- error: cannot create Lean-visible anchor 'AnchorCollision.theory' for type theory
'AnchorCollision': a Lean declaration with that name already exists -/
#guard_msgs (whitespace := lax) in
declare_type_theory AnchorCollision where
  syntax_sort Obj
